### ISSUE TITLE
Fix Implicits current implementation to not require initial reference

### ISSUE THREAD

**Issue by JorgeCastilloPrz** [kategory/kategory#118]
Following problems reported on #105, we need to find the way to avoid the requirement for holding a reference of any implicit instance prior to make it work as an implicit inside any class, and not crash at runtime. Check the linked issue for more details.

**Comment by pakoito** [comment]
We need metaprogramming to avoid this problem. If we could PoC a solution based off an existing plugin like AllOpen it'd be great.

**Comment by JorgeCastilloPrz** [comment]
Let me take this one.

**Comment by ffgiraldez** [comment]
Resolved in #126

**Comment by pakoito** [comment]
The solution in #126 doesn't fix the underlying problem we have with instantiation. @JorgeCastilloPrz is going to take a look at a compiler-plugin driven solution rather than the actual runtime lookup one.

**Comment by ffgiraldez** [comment]
sorry

**Comment by pakoito** [comment]
Don't have to, it's hard to keep up with all the sub-projects happening on the project ATM :D

**Comment by pakoito** [comment]
Completed by #264
